### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by celicoo** [scoutforpets/ember-fullcalendar#1]
This plugins support change the default language? I would like to use "pt-BR".

Thanks.

**Comment by jamesdixon** [comment]
I haven't tested it specifically, but it should support any configuration option currently supported by FullCalendar and FullCalendar scheduler. Let me know if it doesn't work.

**Comment by celicoo** [comment]
Passing lang="pt-br" doesn't work, unfortunately.

**Comment by jamesdixon** [comment]
are you loading the language file as [described here](http://fullcalendar.io/docs/text/lang/)? Currently, the addon doesn't support loading those language packs automatically, but happy to accept a PR if it's something you'd like to implement.

**Comment by celicoo** [comment]
Yes.

I'll clean my node_modules and bower_components and try again.  It might make a difference.

**Comment by celicoo** [comment]
Great, now is working! :dart:

**Comment by jamesdixon** [comment]
Glad you were able to figure it out!
