### ISSUE TITLE
problem during installation

### ISSUE THREAD

**Issue by BenjaminHorn** [scoutforpets/ember-fullcalendar#20]
after  `ember install ember-fullcalendar` I am getting

> Installed packages for tooling via npm.
> /home/me/projects/x/node_modules/ember-fullcalendar/blueprints/ember-fullcalendar/index.js:5
>    return this.addBowerPackageToProject('fullcalendar', '^2.7.3').then(() => {
>                                                                         ^
> Unexpected token )

Looks like arrow functions are not supported.
https://github.com/scoutforpets/ember-fullcalendar/blob/master/blueprints/ember-fullcalendar/index.js#L5

**Comment by rliebeskind** [comment]
What version are you using?  I encountered this as well using ember-cli v2.5.  Have a fix (which is to remove the ES6 syntax) and will make a PR asap.

**Comment by rwwagner90** [comment]
I believe this depends on node version

**Comment by rliebeskind** [comment]
could be true.  I am using node v0.12.4 and ember-cli 2.5 and experienced the same issue.  There is a PR with the fix now.

**Comment by rwwagner90** [comment]
@rliebeskind I am saying that the fix would be to use a newer version of node. Is there a reason you need to be on that specific node version?

**Comment by rliebeskind** [comment]
That is a possible solution. I believe the fix will work with current and previous versions of Node. Isn't that  better?

**Comment by rliebeskind** [comment]
@rwwagner90 That may be a solution. I believe the fix in my PR will work with current and previous versions of Node. Isn't that better?

**Comment by rwwagner90** [comment]
@rliebeskind just trying to understand why you wouldn't want to update node? There are several things like this that will bite you, probably with several addons, and rather than fixing them all, updating may be helpful. The PR is probably fine, but trying to help you out on upgrading here 😄

**Comment by rliebeskind** [comment]
@rwwagner90  thanks very much for the information.  I will keep it in mind.  Indeed, at the moment I do not want to shake the version tree...

**Comment by BenjaminHorn** [comment]
@rwwagner90 my node version must be the problem. but for backward compatibility I think the [PR](https://github.com/scoutforpets/ember-fullcalendar/pull/21) should be merged.

**Comment by jamesdixon** [comment]
@BenjaminHorn going to keep this open until the PR is merged
