### ISSUE TITLE
full calendar fails in IE11 - Object.assign not supported

### ISSUE THREAD

**Issue by rliebeskind** [scoutforpets/ember-fullcalendar#23]
I had to change line 123 in full-calendar.js in order to fix this problem:

it was:

      Object.assign(
        this.get('options'),
        this.get('hooks')
      );

the above fails on IE11.

I replaced it with:

$.extend(Object,this.get('options'),this.get('hooks'));   

this works in IE and does not break Chrome nor FF.

**Comment by jamesdixon** [comment]
Closed via 47220e72ce3eb3b461f911b0ca7f6b16c26d4798
