### ISSUE TITLE
Is eventSources supported ?

### ISSUE THREAD

**Issue by Moxide** [scoutforpets/ember-fullcalendar#24]
Hello,
I tried to declare some events, using the **eventSources** parameter, but nothing is displayed.
I took a look at the code and it seems that **eventSources** is taken into account, but no observer is attached to it. Could this be related ?
Thanks.

**Comment by jamesdixon** [comment]
@Moxide sounds like that's most likely the issue. I don't have time to modify this at the moment, but more than happy to accept a PR. Thanks!

**Comment by jamesdixon** [comment]
Closed via 47220e
