### ISSUE TITLE
Options not working

### ISSUE THREAD

**Issue by Blackening999** [scoutforpets/ember-fullcalendar#28]
Hey guys!

Nice addon, however it doesn't reflect on any option passed in.
I'm laying around with viewName being passed into a component. Ember: 2.5.0

This is a blocker :(

**Comment by jamesdixon** [comment]
@Blackening999 I don't have the latest version (1.0) installed in my application, but running the dummy app and changing views via an action appears to work fine. Can you share some code showing how you're using the addon?

**Comment by Blackening999** [comment]
@jamesdixon I've tested on 0.5.1 . This version was installed by default via "ember install <addon name>".

Sure.
I have a controller:
```js
import Ember from 'ember';

const {
  Controller,
  computed
} = Ember;

export default Controller.extend({

  startDate: null,
  viewName: 'basicDay',

  events: computed(function() {
    return Ember.A([{
     title: 'Event 1',
     start: '2016-05-05T07:08:08',
     end: '2016-05-05T09:08:08'
    }, {
     title: 'Event 2',
     start: '2016-05-06T07:08:08',
     end: '2016-05-07T09:08:08'
    }, {
     title: 'Event 3',
     start: '2016-05-10T07:08:08',
     end: '2016-05-10T09:48:08'
    }, {
     title: 'Event 4',
     start: '2016-05-11T07:15:08',
     end: '2016-05-11T09:08:08'
    }]);
  }),

  actions: {
    changeView(viewName) {
       this.set('viewName', viewName);
     }
    }
});
```

Route is empty in my case (for now)

Template

```hbs
  <button onclick={{action "changeView" "month"}}>Month</button>
  <button onclick={{action "changeView" "agendaWeek"}}>Week</button>
  <button onclick={{action "changeView" "agendaDay"}}>Day</button>
  {{viewName}}
  {{full-calendar viewName=viewName}}
```

**Comment by jamesdixon** [comment]
Can you do me a favor and try installing from `master`? This was upgraded to 1.0.0 and for some reason, it's only showing 0.5.1 on NPM. At first I thought I may have forgotten to publish, but when trying to republish to NPM, it's telling me otherwise.

**Comment by Blackening999** [comment]
@jamesdixon same issue :\

**Comment by Blackening999** [comment]
http://prntscr.com/cqp02c

**Comment by jamesdixon** [comment]
@Blackening999 code looks ok. Can you try cloning the repo and running the dummy app to see if it works for you?

**Comment by jamesdixon** [comment]
When I have some time, I'll give this a shot in my own application.

**Comment by Blackening999** [comment]
pffffff. I'm so sorry for wasting your time. I found the error. What a shame. Some noob named component the same for unused component.
