### ISSUE TITLE
Performance issue with ember 2.7+

### ISSUE THREAD

**Issue by Moxide** [scoutforpets/ember-fullcalendar#29]
Hello,
Just in case someone is facing a huge performance penalty with this addon and ember version 2.7 (and above), you definitely should try to disable prototype extension for arrays :
Add this in your `EmberENV` variable in config/environment.js :
```
 EXTEND_PROTOTYPES:
      {
        Array: false,
      },
```
I realized this while updating an app displaying more than 200 events, from ember 2.6 to 2.7. Display time suddenly jumped from 300ms to 2.5s.
Something must have changed in the way Ember handles `__proto__` property in arrays, and it seems to make events rendering awfully slow in Fullcalendar.

You should read [this post](https://guides.emberjs.com/v2.7.0/configuring-ember/disabling-prototype-extensions/) though, to be aware of the consequences ;-)

There is perhaps another way to fix this, but I have no time to investigate furher...

**Comment by jamesdixon** [comment]
Thanks, @Moxide!

Going to close this since it's not an issue with the addon itself, but appreciate you noting it here.

**Comment by Moxide** [comment]
You're welcome ;-)
