### ISSUE TITLE
Installation Issue - Moment

### ISSUE THREAD

**Issue by getaclue** [scoutforpets/ember-fullcalendar#30]
Hey guys,

It says that moment is not required for using with this addon, but I just installed this addon in a fresh app and I get the following error:

![image](https://cloud.githubusercontent.com/assets/6380439/19447283/cc96d1d4-946a-11e6-8341-50367c6d3226.png)

So, perhaps it is required and the mention in the readme should be modified?

I'm also trying to figure out what the problem with the resolver is, not sure at the moment.

I have a brand new ember 2.8.0 project which has `"ember-resolver": "^2.0.3"`

Cheers,
Alex

**Comment by getaclue** [comment]
Yeap, Issue went away when I installed https://github.com/stefanpenner/ember-moment

**Comment by jamesdixon** [comment]
@getaclue thanks for the report.

Moment is definitely required and due to a ton of other addons loading moment, `ember-cli-moment-shim` should probably be installed. I'm not sure exactly what it was removed.

That said, I'll add it back when I have a chance or more than willing to accept a PR if you have the time :)

Thanks!

**Comment by getaclue** [comment]
@jamesdixon thanks for the prompt reply.

it seems that `ember-cli-moment-shim` is actually a dependency (https://github.com/scoutforpets/ember-fullcalendar/blob/master/package.json#L28) ... not sure why it was not installed though... I didn't get an error or anything. I'll try to redo a brand new ember project and add this addon, once again, to see if there was an error and I simply missed it. Odd.

At the same time, looking at it, `ember-cli-moment-shim` is at `2.2.0`... should we bump that?

I can do a PR for the Readme change though. I'll do it a bit later if nobody beats me to it =)

Cheers,
Alex

**Comment by jamesdixon** [comment]
@getaclue I believe this is no longer an issue. Going to close, but feel free to re-open if that isn't the case. Thanks!

**Comment by kevwilde** [comment]
Hi, please consider reopening this issue. I have had the same problem with a fresh install.Seperately installing `ember-cli-moment-shim` fixed the issue. Thanks!
