### ISSUE TITLE
Depricated getowner-polyfill

### ISSUE THREAD

**Issue by Prabhakar-Poudel** [scoutforpets/ember-fullcalendar#35]
Are you planing on doing something for the deprecated warning?
Should not be much of a problem to fix.

**Comment by jamesdixon** [comment]
@Prabhakar-Poudel a PR would be greatly appreciated!

**Comment by Prabhakar-Poudel** [comment]
@jamesdixon Are you supporting ember lesser than ember@2.3?

**Comment by jamesdixon** [comment]
Resolved via 937f205
