### ISSUE TITLE
eventRender called after event is placed

### ISSUE THREAD

**Issue by Prabhakar-Poudel** [scoutforpets/ember-fullcalendar#48]
Originally reported at [full-calendar issues](https://github.com/fullcalendar/fullcalendar/issues/3633).
Two methods supported by FC are [eventRender](https://fullcalendar.io/docs/event_rendering/eventRender/)  and [eventAfterRender](https://fullcalendar.io/docs/event_rendering/eventAfterRender/).
Surprisingly in `ember-fullcalendar` the **eventRender** callback is executed after all events have been placed in the DOM, as opposed to the ideal behavior on FC documentation.

[Here is fiddle using FC ](https://jsfiddle.net/Prabhakar_p/gx4hzwvz/1/)

and here is [ember twiddle for the same](https://ember-twiddle.com/66983b96878e3c54b24970b464fa5b71?openFiles=controllers.application.js%2C) using ember-fullcalendar.

Now try editing events in both examples and see how ember version is not working as expected.

@jamesdixon Could you see for this sometime soon?

**Comment by jamesdixon** [comment]
@Prabhakar-Poudel thanks for the report and the reproduction. Unfortunately, I don't have time at the moment to dig into this. If you happen to solve the issue, a PR would be much appreciated. Thank you!

**Comment by jamesdixon** [comment]
@Prabhakar-Poudel I saw your fix, but my concern is that removing the run loop could have adverse affects elsewhere. I haven't been able to test this across the board yet.

Here's a good intro to the run loop: https://guides.emberjs.com/v2.16.0/applications/run-loop/ (if you're curious as to why it's used)

**Comment by Prabhakar-Poudel** [comment]
@jamesdixon Thanks for the response. But I do have had problems with run loops in the past. Usually `run-loops` are cheap guns. They work great and get things done in handy. But is very unreliable for many different kind of situations.
Having said that, I had to go ahead and work with my clone of the reppo. And so far in about 6 months I have not seen any problem removing the run loop.

**Comment by jamesdixon** [comment]
@Prabhakar-Poudel I'm not sure I agree with your opinion of run loops, but to each his own 👍  Regardless, I'm about to push out an updated version of this package and after that, I'll do some more testing with your fix. I appreciate the contribution!
