### ISSUE TITLE
Unable to set locale

### ISSUE THREAD

**Issue by hugoruscitti** [scoutforpets/ember-fullcalendar#62]
Hi, i try to change the default locale to 'es' by using this sentence (docs here https://fullcalendar.io/docs/text/locale/):

```
Ember.$('.full-calendar').fullCalendar({locale: 'es'});
```

But i see ember-fullcalendar don't include the `locale-all.js` file (https://github.com/scoutforpets/ember-fullcalendar/blob/master/index.js#L16), then i try to add this file in my local copy of the project, but i see another error:

![testfullcalendardeprecationmessage 2017-08-18 00-53-30](https://user-images.githubusercontent.com/99183/29443630-aa04fed6-83af-11e7-9276-52550c8b0e4b.png)

Any advice?

**Comment by jamesdixon** [comment]
resolved by #64
