### ISSUE TITLE
Upgrading full-calendar to v4

### ISSUE THREAD

**Issue by jir-f** [scoutforpets/ember-fullcalendar#76]
Just wondering about the status of the library and if there are any plans on upgrading the `full-calendar` version to 4.x? 

I'm currently working on a project that needs to use the calendar component but I prefer using the version 4 of full calendar that doesn't use JQuery. 
I noticed that @lan0 had forked the repo and upgraded to v4. Not sure if he has plans on opening a PR to this repo but I would be happy to help in upgrading full calendar to v4.2.0.

**Comment by lan0** [comment]
Thanks for getting the ball rolling on this! I definitely want to open a PR.

My fork currently uses `4.0.0-alpha.4`, with the beta release the functionality got broken up into plugins.

I got a working prototype with 4.0 running locally now, but it would probably be wise to update the addon's API to be more like the other third party components (React, Vue, Angular).

**Comment by jamesdixon** [comment]
Hello! I'd love to get this upgraded but currently, don't have the time right now. If either of you would like to spearhead the effort, I'm more than happy to give feedback.

Thanks!
James

**Comment by jir-f** [comment]
@lan0 This was the only place that I can reach to you 🙄. I created a branch from your fork, and I had some additions that I wanted to see if you can add. What do you think the best way to do that?

**Comment by Mithrilhall** [comment]
Are either of you working on this (@jir-f & @lan0)?

**Comment by lan0** [comment]
See #77 @Mithrilhall

**Comment by xiwcx** [comment]
hi all, i wrote a new plugin based off of v4 if that's of any interest: https://github.com/Mariana-Tek/ember-fullcalendar

**Comment by lan0** [comment]
Support for FC v4 released in 2.0.0
